site_name: GNN-RL Pipeline
site_url:
nav:
  - "Get Started":
    - "Overview": overview.md
    - "Installation": Installation.md
    - "Introduction by example": intro.md
  
  - Model DNN as Graph:
      - Simplified computational graph: graph/simplified.md
      - Hierarchical graph: graph/hierarchi.md
      - Build your customized graph: graph/custom.md
#      - Example : graph/example.md
      - "Torch-geometric":  empty.md
      - "DGL":  empty.md

  - "Graph Neural Network":
      - GCN-based graph encoder: gnn/graph_encoder.md
      - Multi-stadge graph neural network:  gnn/multigcn.md
      - Build your customized GNN:  gnn/multigcn.md
      - Embed computational graph: empty.md

  - "GNN-RL in Model Compression":
      - "GNN-RL network pruning": compression/pruning.md
      - "AGMC": empty.md

  - "Customize GNN-RL Pipeline":
      - GNN-RL on federated learning:  empty.md
      - Rewrite the Graph Environment: empty.md

  - About Us:
      - SwAPP: swapp.md

  - API:
      - gnnrl.lib: empty.md
      - gnnrl.graph_env: empty.md
      - gnnrl.data: empty.md
      - gnnrl.models: empty.md
      - gnnrl.utils: empty.md
      - gnnrl.networks: empty.md
  # - "Model DNN as Graph": 
  #   - "Graph Neural Network Pakadge":
  #     - "GNN Overview":  4.md
  #     - DGL:  5.md
  #     - Torch-Geometric: 6.md
  #   - "Graph Neural Network Pakadge1":
  #     - "GNN Overview":  4.md
  #     - DGL:  5.md
  #     - Torch-Geometric: 6.md
  



theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
